### ISSUE TITLE
"Articles" organization

### ISSUE THREAD

**Issue by bruno-f-cruz** [bonsai-rx/docs-wip#6]
The way docfx.json is set up right now, articles are expected to:
- be written as a .md file and stored in ~/articles
- included figures have to be included in ~/figures

I propose the following structure:
all files included in the article (.md, pictures, maybe even workflows?) should follow:
~/articles/my_new_article/my_newarticle.md
~/articles/my_new_article/fig1.png
~/articles/my_new_article/workflow1.bonsai
etc...

I believe this will make the articles much more self-contained and easy to maintain

**Comment by taunsquared** [comment]
Based on discussions in the Tuesday documentation meetings, here's what we agreed to: 

 - articles will be written as .md files and stored in ~/articles
 - any included figures will be stored in ~/images and will be named using the pattern [article filename]-[figure name].svg
 - any included workflows will be stored in ~/workflows and will be named using the pattern [article filename]-[workflow name].bonsai

TO DO: 
 - style convention re figures needs to be added to the style guide in the READ.ME file on the main branch of the docs-wip repo 
 - style convention re workflows needs to be updated to style guide
